### ISSUE TITLE
'node-gyp configure build' Exit status 1

### ISSUE THREAD

**Issue by MatthewMcLeod** [DominicBoettger/autocomplete_example#5]
I am looking into different autcomplete examples. When I attempted the npm install, I recieved the error:
'node-gyp configure build' 
Exit status 1

and said to notify the author. 

Can you please recheck that the files are working. I would be very interested in trying it out.

**Comment by DominicBoettger** [comment]
Hi,

i think if you change the packages json and the express version it could work.
But i suggest to use select2 with websockets. 

Best regards
Dominic
